### ISSUE TITLE
Create separate json file for the monster db

### ISSUE THREAD

**Issue by SlackingVeteran** [AddictivoH/MSL-Data-Nest#1]
Hi Addi, I was wondering if you could keep the monster db in separate json file than saving db as json object within the js file. it'd help a lot for other devs to source to your db for creating new things based on db.
I am currently working on a discord bot and was planning to source data from your github page, then I found out you have saved json db within the js file as a constant making it difficult to use as a source.

**Comment by AddictivoH** [comment]
here is the "json" data
https://script.googleusercontent.com/macros/echo?user_content_key=wMGv99y9sYj2kYTPtjR4-HMf98J2sKUiHinnEP7gv8RzIZrczRT2rt0lbDGMJwwsH_h-mXvbNy5e9Whwp3VzFfB-EsqrT6YNm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnEh0_wRGZQULIrMT8QyXxZoUnOz49BHBOP2FytDG99siyzIhBwrv746_vyOGUXPmPz62ACkgbrsk&lib=MjvBt6r9iM7YtdkOvP-WBqjIRRB0ZxSWX

**Comment by wssyncmldm** [comment]
Thanks a lot for getting back with the json file url. Quick question, will the same url work if you update your json in future?

**Comment by AddictivoH** [comment]
Yes, it is just a URL to a Google script to fetch the data from Google
sheets as Json, so any change in the Google sheet reflects in the JSON
